name: Reference latest Smooks artifacts

on:
  schedule:
    - cron: '30 14 * * 0'
  workflow_dispatch:

permissions: { }
jobs:
  build:
    if: github.repository == 'smooks/smooks-fixed-length-cartridge'
    permissions:
      contents: write
      pull-requests: write
      actions: write

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: |
          if mvn help:evaluate -Dexpression=project.version -q -DforceStdout | tail -1 | grep -q -- -SNAPSHOT ; then
            mvn -DgenerateBackupPoms=false -DnextSnapshot -DprocessAllModules=true versions:set
          fi
          mvn versions:use-latest-snapshots -DgenerateBackupPoms=false -Dincludes=org.smooks*
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: master
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: reference latest Smooks artifacts"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: ref-latest-smooks-artifacts
          title: "Reference latest Smooks artifacts"
          reviewers: tfennelly,cjmamo
          sign-commits: true
